project:
  type: website

website:
  title: "AdventOfCode"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: 2024/index.qmd
        text: "2024"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



